# 1. k: v       k,v 之间是空格区分
# 2. 属性有层级关系，使用下一行，空两个空格 (用回车 和 空格 控制层级关系，只要左侧是对齐的，代表同一层级的属性
# 3. 空格的数量不重要，但只要左侧对齐，就代表同一层级

server:
  port: 9999

spring:
  servlet:
    multipart:
      max-file-size: 10MB
  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: aaaa
    name: bbbb
    password: bbbb

person:
  name: zhangsan
  age: 18
  birthday: 2010/10/10 12:12:12
  like: true
  child:
    name: lisi
    age: 20
#   birthDay: 2018/10/10         # 这里就光写日期，不写时间了
    birth-day: 2018/10/10         # 符合驼峰命名法的，推荐用 -
#   text: ["abc", "def"]
    text:
      - abc
      - def
      # 大文本
      - ｜
        gdsgsadfadshgiksdagdksgaklhgdskhagidsoghosaghdsi
        fagdsagdsghdshd
      - >
        aaaaaa
        bbbbb
        ccc
  dogs:
    - name: xiaohei
      age: 3
    - name: xiaobai
      age: 3
  cats:
    c1:
      name: xiaolan
      age: 3
    c2:
      name: xiaolv
      age: 2
    c3: {name: xiaohua, age: 2}       # 对象也可用大括号表示

# --- 相当于单独分割了一个文件

